Задача 1
Pirchesko/C_Sharp pull request #1
Opened 2022-10-03 20:10 UTC by Pirchesko

2022-10-04 08:24 UTC, Ningyo requested changes

2022-10-04 08:24 UTC, Ningyo commented on Lab1/Contender.cs
> +﻿using System;
лишние файлы - в гитигнор

2022-10-04 08:24 UTC, Ningyo commented on Lab1/Contender.cs
> +            //Console.WriteLine($"{frist_name} {last_name}");
закомментированный код не нужен

2022-10-04 08:24 UTC, Ningyo commented on Lab1/Contender.cs
> +            frist_name = Randomizer.GetRandomFristName();
в списке должны быть только **уникальные** претенденты

2022-10-04 08:24 UTC, Ningyo commented on Lab1/Contender.cs
> +            mark = Randomizer.GetRandomMark();
нет абсолютной гарантии, что номера будут уникальны

2022-10-04 08:24 UTC, Ningyo commented on Lab1/Contender.cs
> +        private string frist_name = null; //Фамилия
можно сделать проперти с приватным сеттером

2022-10-04 08:24 UTC, Ningyo commented on Lab1/Contender.cs
> +    internal class ContenderComparer : IComparer<Contender>
два класса в одном файле - зло

2022-10-04 08:24 UTC, Ningyo commented on Lab1/Friend.cs
> +        public CompareType CompareContenders(Hall hall, IContenderForPrincess contender1, IContenderForPrincess contender2)
холл можно сделать просто полем принцессы, и не передавать каждый раз

2022-10-04 17:07 UTC, Ningyo requested changes

2022-10-04 17:07 UTC, Ningyo commented on Lab1/Contender.cs
> +        //Инициализировать Contender рандомными именами и фамилиями? true - да; false - нет
студия не будет подсвечивать комментарии при наведении на функцию. она подсвечивает саммари. полагаю, если вы тут даже параметры описали, то имелось в виду, что это описание должно быть саммари

2022-10-04 17:07 UTC, Ningyo commented on Lab1/Friend.cs
> +            if ((hall.CheckContederInHall(contender1_) != false) || (hall.CheckContederInHall(contender2_) != false))
1. чем != false отличается от == true?
2. очень странно читается, на самом деле "если претендент1 есть в холле, или претендент2 есть в холле, то вернуть 'не знаю'" это точно правильное условие?

2022-10-04 17:07 UTC, Ningyo commented on Lab1/Friend.cs
> +            Contender contender1_ = (Contender)contender1;
здесь и в подобных местах: не понимаю, зачем вы добавляете нижнее подчёркивание в названия переменных. в шарпах принято именовать переменные в camelCase; функции, классы и т.п. - в PascalCase. нижнее подчёркивание используется только для приватных полей, и в начале, а не в конце

2022-10-04 17:07 UTC, Ningyo commented on Lab1/Friend.cs
> +            Contender contender1_ = (Contender)contender1;
можно использовать var - у вас в этой же строке явно выводится тип

2022-10-04 17:07 UTC, Ningyo commented on Lab1/Friend.cs
> +            if (contender1_.GetMark() > contender2_.GetMark())
простой if\else можно сократить до тернарного выражения ?:

2022-10-04 17:07 UTC, Ningyo commented on Lab1/Hall.cs
> +namespace Lab1
не самое удачное название, у вас эта задача в течение всех лаб будет развиваться)

2022-10-04 17:07 UTC, Ningyo commented on Lab1/Hall.cs
> +        private const int contenders_count = 100; //количество претендентов
я бы советовала быть осторожным с комментариями в одну строку с кодом. легко вылезают за пределы одного экрана при любом изменении. у строки кода появляется на одну возможную причину для изменения больше - при ревью такого кода приходится дополнительно думать, комментарий ли только изменился, или код тоже.
в этом конкретном случае они вообще больше на саммари походят

2022-10-04 17:07 UTC, Ningyo commented on Lab1/Hall.cs
> +        private const int contenders_count = 100; //количество претендентов
это сишный стиль. пересмотрите в лекциях материал про код стайл, пожалуйста. там было несколько ссылок.

2022-10-04 17:07 UTC, Ningyo commented on Lab1/Hall.cs
> +            var sorted = from c in hall orderby c.GetMark() select c;
OrderBy возвращает IOrderedEnumerable<TSource>, не изменяя порядка элементов в исходном списке. так что вам не обязательно здесь создавать дополнительно sorted

2022-10-04 17:07 UTC, Ningyo commented on Lab1/Hall.cs
> +            Contender contender = hall[0];
что будет, если список окажется пуст?

2022-10-04 17:07 UTC, Ningyo commented on Lab1/Hall.cs
> +                if ((contender_.GetFristName() == contender.GetFristName()) && (contender_.GetLastName() == contender.GetLastName()) && (contender_.GetMark() == contender.GetMark()))
очень тяжело читать, имена contender_ и contender практически не различаются

2022-10-04 17:07 UTC, Ningyo commented on Lab1/Hall.cs
> +            foreach(Contender contender_ in hall)
не обязательно вручную перебирать весь холл, можете воспользоваться одним из стандартных методов для поиска элемента в списке

2022-10-04 17:07 UTC, Ningyo commented on Lab1/Hall.cs
> +        public int GetHappyMark(IContenderForPrincess contender)
1.по условию, принцесса может не выбрать никого. не сломается в этом месте?
2.странно, что холл считает, насколько принцесса счастлива
3.функция счастья не соответствует задаче - перечитайте, пожалуйста, условие

2022-10-04 17:07 UTC, Ningyo commented on Lab1/IContender.cs
> +    internal interface IContender
не вижу, где он используется

2022-10-04 17:07 UTC, Ningyo commented on Lab1/Princess.cs
> +        //private IContenderForPrincess contender = new Contender(false); //Интерфейс претендента, не позволяющий вызвать метод GetMark()
закомменченный код нужно удалять

2022-10-04 17:07 UTC, Ningyo commented on Lab1/Princess.cs
> +        public PrincessMark ThinkAboutContender(Hall hall, Friend friend, IContenderForPrincess contender)
здесь тоже холл и подругу не обязательно передавать в параметрах каждый раз. принцесса может просто знать о них с самого начала

2022-10-04 17:07 UTC, Ningyo commented on Lab1/Princess.cs
> +            if (top_contenders.Count != 0)
где есть возможность, лучше избегать лишних уровней вложенности, чтобы проще читалось. здесь можно перевернуть условие и вынести наверх короткий блок, который сейчас в else. т.к. там стоит return, дальше можно ни else не писать, ни лишние скобки.
if(условие1)
{
foo1();
return value1;
}
else
{
foo2();
return value2;
}

то же самое, что
if(условие1)
{
foo1();
return value1;
}

foo2();
return value2;
только блоков меньше

2022-10-04 17:07 UTC, Ningyo commented on Lab1/Program.cs
> +            for (i = 0; i < 37; i++)
magic numbers - потенциальные источники проблем и недопониманий. лучше вынести или в приватные константы, если нигде больше не используются, или в общие для всей программы. с понятным именем и описанием, если требуется пояснение

2022-10-10 07:19 UTC, Pirchesko commented on Lab1/Friend.cs
> +            Contender contender1_ = (Contender)contender1;
Конкретно в этом моменте надо было привести к нужному типу. Вариант такой:
contender1 = (Contender)contender1;
contender2 = (Contender)contender2;
Компилятору не устроило. А везде вставлять скобки к приведению типу немного не очень смотрится. Один раз сделал и забыл. Придумал самое близкое название чтобы выглядело похоже и всё. Например можно сделать так, чтобы подчеркивание было не последним. Так лучше смотрится:
Contender contender_1 = (Contender)contender1;
Contender contender_2 = (Contender)contender2;

2022-10-10 09:39 UTC, Pirchesko commented on Lab1/Hall.cs
> +        public int GetHappyMark(IContenderForPrincess contender)
1 - действительно так, над этим я поработаю

2 - Я просто не знаю на кого можно повесить эту задачу. Принцесса не должна это делать, она не может иметь доступа к оценке. Подруга её, должна отвечать только на 1 вопрос, кто круче из 2ух претендентов. Хотя можно на самом деле повешать на неё задачу, но тоже как-то странно получится. Вешать задачу на Рандомайзер - странно, он отвечает только за рандомные имена и фамилии и рандомную оценку. Далее Холл. В нем толпятся люди, наверное (условно говоря) ему и виднее кто из них насколько крут. Мне кажется на него навешивать задачу о распределении счастья - нелогично и неправильно. Contender точно не подойдет. Соотвественно только Friend и Hall более менее подходят для этой задачи. Либо надо создавать какой-то ещё дополнительный класс который бы отвечал за полученное счастье.

Однако, в задаче кое-что ещё намекнуло что должно отвечать за получение уровня счастья: "После того как принцесса сделает выбор она сможет выйти в прихожую и понять кого она выбрала.". Явно намекает на то, что Холл должен отвечать, кто самый крутой ("Претенденты толпятся в прихожей (Hall)")

Ещё для меня оценка и счастье - это разные вещи. Объясняю почему на основе задачи:
"Все этом претенденты, как говорят математики, образуют вполне упорядоченное множество по своим личным качествам (все они отличаются друг от друга)" - первое что звучит, это то, что все они ОТЛИЧАЮТСЯ друг от друга. Что это значит в контексте этих условий? Это означает, что выдавать оценку качества надо везде разную, раз они отличаются друг от друга. А значит подход, что качество - есть уровень счастья в корне не подходит, об этом говорит вот это предложение: 
"Уровень счастья определяется так: за лучшего жениха принцесса получает 100 баллов, за второго по хорошести – 99 и так далее до 51. Если выбранный кандидат на 50 месте или ниже, то, принцесса понимает, что вышла за неудачника, мучается всю жизнь, и получает 0 баллов счастья. Если не выбрала никого, то 10."
Т.е. если оценка была бы у претендентов такая же как шкала счастья у толпы народа, стоящих в холле, это бы не отвечало бы условиям задачи, так как сказано "(все они отличаются друг от друга)".
Т.е. однозначно приходим к выводу, что уровень счастья и оценка качества - разные вещи, а значит реализовать их можно по-разному.

Как можно было бы реализовать? Просто также выдавать всем оценку рандомную от 1 до 100, а потом просто игнорировать всё что меньше 51 и превращать 0. Однако я решил что проще давать рандом (от 0 до INT_MAX), а просто потом нормализировать. Это делается с помощью отсортированного списка Hall. И их индекс - это как раз уровень (сортировка от наименьшего к наибольшему +1). Для меня это проще. Единсвтенное, что я не учёл, так это как раз игнорирование всего что меньше. Это я исправил:

`ContenderComparer cc = new ContenderComparer();`
`//Sort from min to max + 1`
`int index = hallSort.BinarySearch((Contender)contender, cc) + 1; `
`if (index <= 50) index = 0;`

2022-10-12 17:51 UTC, Ningyo commented on Lab1/Contender.cs
> +        public string GetFristName()
можно сделать просо проперти с приватным сеттером

2022-10-12 17:51 UTC, Ningyo commented on Lab1/Randomizer.cs
> +        private const string pathFristName = "D:\\Files\\Visual Studio\\C#\\Lab1\\frist_names.txt";
вы указали полное имя. если я скачаю ваш репозиторий и попытаюсь запустить, что будет?

2022-10-12 17:51 UTC, Ningyo commented on Lab1/Contender.cs
> +            frist_name = Randomizer.GetRandomFristName();
всё ещё не очевидно из кода, почему здесь должно получиться что-то уникальное

2022-10-12 17:52 UTC, Ningyo commented on Lab1/Contender.cs
> +        private string frist_name = null; //Фамилия
всё ещё актуально

2022-10-12 17:55 UTC, Ningyo commented on Lab1/Friend.cs
> +        private Hall hall;
1.приватные поля именуются с _
2.если вы не планируете менять это поле в процессе жизни принцессы, то readonly

2022-10-12 17:55 UTC, Ningyo commented on Lab1/Friend.cs
> +            if ((hall.CheckContederInHall(contender1_) != false) || (hall.CheckContederInHall(contender2_) != false))
1.если булево поле необнуляемое, то даже == true писать не обязательно на самом деле

2022-10-12 17:58 UTC, Ningyo commented on Lab1/Friend.cs
> +            Contender contender1_ = (Contender)contender1;
нет. это не смотрится лучше. это не подходит по стилю. придумайте другие названия, чтобы они соответствовали смыслу, а не только цифрой различались.
вы приводите к другому типу. где гарантия, что вам передали объект именно этого типа? что, если передадут другую реализацию IContenderForPrincess ?

2022-10-12 18:01 UTC, Ningyo commented on Lab1/Hall.cs
> +        private const int contenders_count = 100; //количество претендентов
отлично. только теперь у вас не кол-во претендентов, а "посчитай претендентов". должно быть существительное, а не глагол

2022-10-12 18:06 UTC, Ningyo commented on Lab1/Contender.cs
> +        public Contender(bool check_init)
опять сишный стиль

2022-10-12 18:06 UTC, Ningyo commented on Lab1/Hall.cs
> +            Contender contender = hall[0];
вопрос актуален. теперь вы возвращаете какого-то дефолтно заполненного претендента. и как понять тогда, что больше претендентов не будет? можно сколько угодно вызывать у холла GetNextContender

2022-10-12 18:14 UTC, Ningyo commented on Lab1/Hall.cs
> +        public int GetHappyMark(IContenderForPrincess contender)
1.пока доработки не вижу
2.скажите, ваше счастье определяете вы или ваш коридор? независимо от того, можете вы количественно его измерить или нет? выйти в холл и понять, кого она выбрала. кто здесь действующее лицо? кто понимает? холл?

2022-10-12 18:14 UTC, Ningyo commented on Lab1/Hall.cs
> +            return hall.Exists(x => x.Equals(contender)) ? true : false;
что возвращает Exists? вы уверенны, что здесь нужно тернарное выражение?

2022-10-12 18:14 UTC, Ningyo commented on Lab1/Princess.cs
> +        public PrincessMark ThinkAboutContender(Hall hall, Friend friend, IContenderForPrincess contender)
всё ещё актуально

2022-10-12 18:17 UTC, Ningyo commented on Lab1/Randomizer.cs
> +        private const string pathFristName = "D:\\Files\\Visual Studio\\C#\\Lab1\\frist_names.txt";
здесь и в других местах - у вас опечатка F**r**ist

2022-10-12 18:17 UTC, Ningyo commented on Lab1/Program.cs
> +            for (i = 0; i < 37; i++)
всё ещё актуально

2022-10-12 19:38 UTC, Pirchesko commented on Lab1/Contender.cs
> +        private string frist_name = null; //Фамилия
Не получается никак сделать проперти, потому что либо компилятор жалуется на ошибки, либо во время запуска происходит что-то странное:

Stack overflow.
Repeat 24088 times:
--------------------------------
   at Lab1.Contender.set_fristName(System.String)
--------------------------------
   at Lab1.Contender.InitContender()
   at Lab1.Contender..ctor()
   at Lab1.Hall..ctor()
   at Lab1.Program.Main(System.String[])

public string fristName { get => fristName; private set { fristName = null; } }
public string lastName { get => lastName; private set { lastName = null; } }
private int mark = -1;

2022-10-12 19:43 UTC, Pirchesko commented on Lab1/Friend.cs
> +            if ((hall.CheckContederInHall(contender1_) != false) || (hall.CheckContederInHall(contender2_) != false))
Если в холле есть какой-то претендент (назовем его первым) или если есть в холле ещё какой-то претендент (назовём его вторым), то подруга принцессы не должна будет сравнивать их между собой
По-другому говоря, подруга проверяет, чтобы принцесса спрашивала только о тех людях которые у нее были или находятся сейчас на свидании. Т.е. их не должно быть в любом случае в Холле. Это я и проверяю

2022-10-12 20:22 UTC, Pirchesko commented on Lab1/Hall.cs
> +            Contender contender = hall[0];
Если кончатся Contenders то вернется пустой Contender (он уникальный, и не должен содержаться в общем потоке Contender, так как там все поля инициализируются). Для него специальный конструктор Contender(false) как раз для того чтобы отличать от других. Соответственно, как только такой появился, значит они кончились

2022-10-12 20:43 UTC, Pirchesko commented on Lab1/Hall.cs
> +        public int GetHappyMark(IContenderForPrincess contender)
1: Я посмотрел код и выяснил, что в целом dont_know и worse игнорируются в моём алгоритме (37% пропускаем, а дальше самого лучшего беру), однако, возможно понадобятся, если я захочу придумать свой алгоритм, где бы меня интересовали эти варианты ответа. Если так получилось, что попался dont_know, то он просто останется в памяти у принцессы как самый худший, раз сравнить нельзя. 
2: Холл предоставляет ответ, сколько счастья получит Принцесса. Можно конечно просто метод сделать у принцессы который вызовет метод всё равно у холла, просто странно будет выглядеть

2022-10-13 06:18 UTC, Ningyo commented on Lab1/Contender.cs
> +        private string frist_name = null; //Фамилия
что такое сеттер, скажите, пожалуйста. и что он делает. и что происходит в вашем коде, если вы хотите сделать private set { fristName = null; }

2022-10-13 06:34 UTC, Ningyo commented on Lab1/Friend.cs
> +            if ((hall.CheckContederInHall(contender1_) != false) || (hall.CheckContederInHall(contender2_) != false))
ооох какой-то у вас интересный способ. тогда хотя бы в саммари к методу CheckContederInHall нужно дописать, что вы имеете в виду под "претендент в холле". я лично по названию подумала, что вы проверяете, что претендент вообще знаком холлу, что это не левый кто-то без очереди влез

2022-10-13 06:43 UTC, Ningyo commented on Lab1/Friend.cs
> +            Contender contender1_ = (Contender)contender1;
cont1 и cont2. моё замечание всё ещё в силе. сокращения - зло. сформулируйте для себя, в чём их особенность, а потом подберите название

вот вы добавили проверку is Contender. но ответ вашей функции не однозначен. если у вас передали неправильного претендента - не того ли типа, которого вы (неявным, что плохо, образом) ожидали, или непосещённого претендента, у вас вернётся dont_know. и дальше вы с ним ничего не делаете. вы можете передать сколь угодно некорректные данные, спокойно их обработать и выдать ответ, что принцесса хочет остаться одна. замалчивать проблемы - плохая тактика

2022-10-13 06:51 UTC, Ningyo commented on Lab1/Hall.cs
> +            Contender contender = hall[0];
где гарантия, что он уникален? не вижу никаких причин, почему мы я не могла заполнить весь список пустыми претендентами

2022-10-13 07:01 UTC, Ningyo commented on Lab1/Hall.cs
> +            return _hall.Exists(x => x.Equals(contender));
если в холле есть Иван Иванов 10. что будет, если спросить _hall.Exists(x => x.Equals(new Contender("Иван", "Иванов", 10))) ?

2022-10-13 07:01 UTC, Ningyo commented on Lab1/Hall.cs
> +        public int GetHappyMark(IContenderForPrincess contender)
1.худший и несравнимый - разные вещи. вы можете сказать, что хуже - апельсин или табуретка? если worse  как противоположность better я могу понять, даже если вы его не обрабатываете. но "не знаю" вызывает большие вопросы. вы его возвращаете в случаях, когда кто-то пытается некорректно воспользоваться логикой.
2.вы не ответил на мой вопрос) здесь смысл не просто в том, чтобы в принцессе была эта функция, а логика лежала где угодно. вопрос в том, кто имеет право эту логику содержать и почему

2022-10-13 07:01 UTC, Ningyo commented on Lab1/Hall.cs
> +            ContenderComparer cc = new ContenderComparer();
var. и так понятно, что это ContenderComparer

2022-10-13 07:01 UTC, Ningyo commented on Lab1/Program.cs
> +            for (i = 0; i < 37; i++)
всё ещё актуально) если вы назовёте константу skip37 -  понятнее не станет. это всё ещё magic. замечание относилось ко всем остальным меджикам тоже

2022-10-13 07:09 UTC, Ningyo requested changes

2022-10-13 07:09 UTC, Ningyo commented on Lab1/CompareType.cs
> +        better,
PascalCase. не используется в шарпах сишный стиль. ни в функциях, ли в переменных, ни в полях - не используется

2022-10-13 07:09 UTC, Ningyo commented on Lab1/Program.cs
> +            Hall hall = new Hall();
var. и так понятно, какого типа

2022-10-13 07:09 UTC, Ningyo commented on Lab1/Randomizer.cs
> +        private const bool unique = true;
константы в PascalCase, даже приватные

2022-10-13 07:09 UTC, Ningyo commented on Lab1/Randomizer.cs
> +        private static readonly Random rnd = new Random();
сокращения - зло

2022-10-13 07:09 UTC, Ningyo commented on Lab1/Randomizer.cs
> +        private const int _countFirstName = 100;
здесь и в подобных местах. это всё глаголы. "посчитай имена", "храни имена", "перечисли имена". нарушен порядок слов, читается как обычно предложение глагол-дополнение

2022-10-26 15:03 UTC, Ningyo commented on Lab1/Friend.cs
> +            if ((contender1 is Contender) && (contender2 is Contender))
возможно, предыдущее замечание, что приводить плохо, затерялось. так что напишу ещё разок) теперь вы проверяете по is, что вам передали Contender - тогда получается, что в контракте функции вы **обманываете** потребителя этой функции. заявляете, что примере двух IContenderForPrincess, а по факту ожидаете только Contender, и никак иначе. это не проблема пользователя функции, это проблема вашей реализации - вы заявили одно, в выполняете другое. у вас у претендентов уникальные имена. загляните в текст пятой задачи - там ваш ответ. вы можете спросить, кто лучше, по именам

2022-10-26 15:03 UTC, Ningyo commented on Lab1/Program.cs
> +            for (i = 0; i < 37; i++)
оке, хотя бы комментарий. хотя меджики в коде - потенциальные источники проблем, и вы это обязательно увидите, если продолжите их везде писать

2022-10-26 15:09 UTC, Ningyo commented on Lab1/Hall.cs
> +            return _hall.Exists(x => x.Equals(contender));
оке, с override Equals сработает

2022-10-26 15:16 UTC, Ningyo commented on Lab1/Randomizer.cs
> +        private const bool unique = true;
всё ещё актуально. константы в PascalCase без подчёркивания.

2022-11-01 07:48 UTC, merged