Lab3 complete
Pirchesko/C_Sharp pull request #6
Opened 2022-12-20 08:05 UTC by Pirchesko

2022-12-21 13:52 UTC, Ningyo requested changes

2022-12-21 13:52 UTC, Ningyo commented on Lab1/ContenderGenerator.cs
> +        public int ContendersCount()
можно сделать статический класс с общими для всех константами

2022-12-21 13:52 UTC, Ningyo commented on Lab1/Hall.cs
> +            _hall = _contenderGenerator.CreateListContender();
лучше вынести сложную логику из конструктора, чтение претендентов - потенциально долгая или асинхронная операция

2022-12-21 13:52 UTC, Ningyo commented on Lab1/IContenderGenerator.cs
> +        //create list of contenders
это не саммари

2022-12-21 13:52 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/ContenderGeneratorTest.cs
> +        List<Contender> CreateContenderListWithoutUniqueContenders()
не используется, удалить

2022-12-21 13:52 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/ContenderGeneratorTest.cs
> +        bool CheckUniqueListContender(List<Contender> contenders)
можно заменить на fluent assertions containOnlyUniqueItems (или вроде того)

2022-12-21 13:52 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/FriendTest.cs
> +                string firstName = Randomizer.GetRandomFirstName();
вам для тестов не обязательно иметь настоящие данные, тем более список из 100 для подруги. можете сами сформировать список по какой-нибудь простой логике. или положить туда 2-3 заранее вам известных, или заданное кол-во в цикле в убывающем или возрастающем порядке. проще)

2022-12-21 13:52 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/FriendTest.cs
> +            Contender bestContender = hall.GetNextContender();
можно просто var .и так понятно, что это претендент

2022-12-21 13:52 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/FriendTest.cs
> +            CompareType cp = friend.CompareContenders(bestContender, worseContender);
лучше назовите понятно, чем тип писать, но называть cp

2022-12-21 13:52 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/FriendTest.cs
> +            CompareType cp_better = CompareType.Better;
эта переменная бессмысленна, тут можете просто сразу написать Be(CompareType.Better) - название само за себя говорит. magic - это строка или число, непонятно что означающие без знания контекста. использование enum - не magic

2022-12-21 13:52 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/FriendTest.cs
> +            friend.Invoking(f => f.CompareContenders(worseContender, bestContender)).Should().Throw<Exception>().WithMessage("Подруга не может сравнивать претендентов, которые ещё не были у принцессы
лучше перенесите на несколько строк, а то слишком длинно получается, сложно читать, хотя там что-то важное написано, и дочитать таки нужно
```
.Should()
.Throw<Exception>()
.WithMessage(...)
```

2022-12-21 13:52 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/PrincessTest.cs
> +        List<Contender> CreateContenderListForPrincessWhoGet10()
непонятное название. почему здесь 10 получится, что вообще за 10 в контексте списка претендентов? лучше опишите в названии, что такого особенного в претендентах или их порядке

2022-12-21 13:52 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/PrincessTest.cs
> +        List<Contender> CreateContenderListForPrincessWhoGet10()
здесь и в подобных местах

2022-12-21 13:52 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/FriendTest.cs
> +            CompareType cp_better = CompareType.Better;
здесь и в подобных местах

2022-12-21 13:52 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/PrincessTest.cs
> +            princess.Invoking(p => p.FindBestContender()).Should().Throw<Exception>().WithMessage("� �������� ������ ���� ������������!");
кодировка слетела

2022-12-21 13:52 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/FriendTest.cs
> +            friend.Invoking(f => f.CompareContenders(worseContender, bestContender)).Should().Throw<Exception>().WithMessage("Подруга не может сравнивать претендентов, которые ещё не были у принцессы
здесь и в подобных местах

2022-12-21 13:52 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/PrincessTest.cs
> +            List<Contender> contenderList = CreateContenderListForPrincessGetExceptionNoContenders();
обязательно 50 претендентов генерить, чтобы проверить, что претендентов нет? выглядит, что лишнее время и ресурсы зазря тратятся

2022-12-21 13:52 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/FriendTest.cs
> +            _lifetime = new Mock<IHostApplicationLifetime>();
вы его дальше нигде не используете, зачем оно вам? здесь в и тестах холла

2022-12-21 13:52 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/TestHall.cs
> +            List<Contender> contenderList = CreateContenderListForHallTest();
зачем вам здесь 100 претендентов? вы берёте только одного

2022-12-23 16:53 UTC, Pirchesko commented on Lab1/TestFastidiousPrincess/ContenderGeneratorTest.cs
> +        bool CheckUniqueListContender(List<Contender> contenders)
Нашел OnlyHaveUniqueItems()

2022-12-25 07:38 UTC, Ningyo commented on Lab1/Hall.cs
> +            _hall = _contenderGenerator.CreateListContender();
вы меня не поняли) у вас по факту как вызывалась эта логика в конструкторе, так и осталась вызываться из конструктора

2022-12-25 07:40 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/FriendTest.cs
> +                string firstName = Randomizer.GetRandomFirstName();
оке, так уже проще, но вам даже Randomizer не нужен здесь. зачем вам правдоподобное имя, если можно задать любое своё для теста

2022-12-25 07:43 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/PrincessTest.cs
> +            princess.Invoking(p => p.FindBestContender()).Should().Throw<Exception>().WithMessage("� �������� ������ ���� ������������!");
в других местах тоже есть слетевшая. см PrincessTest

2022-12-25 07:45 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/FriendTest.cs
> +                string firstName = Randomizer.GetRandomFirstName();
здесь и в подобных местах

2022-12-25 08:24 UTC, Pirchesko commented on Lab1/Hall.cs
> +            _hall = _contenderGenerator.CreateListContender();
исправил

2022-12-26 13:17 UTC, Ningyo commented on Lab1/TestFastidiousPrincess/FriendTest.cs
> +                string firstName = Randomizer.GetRandomFirstName();
оке, в принцессе пусть останется. хотя по-моему, и там не нужен

2022-12-26 13:17 UTC, merged